import visibilityDilemma from "../assets/images/visibility-dilemma.jpg";
import engagementGap from "../assets/images/engagement-gap.jpg";
import resultsInHibernation from "../assets/images/results-in-hibernation.jpg";

const services = [
  {
    title: "Tokenization of Real Assets",
    features: [
      "We convert physical assets, such as logistics fleets and recycling plants, into security tokens, which represent fractional ownership. These tokens are backed by tangible investments, ensuring stability and long-term value appreciation.",
    ],
    icon: `<svg width="30" height="30" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
    <text x="10" y="40" font-size="40" font-family="Arial" fill="white">1</text>
</svg>
`,
  },
  {
    title: "Investment & Revenue Sharing",
    features: [
      "Investors purchase Alpha Tokens, representing a stake in our asset-backed portfolio. Revenue generated from these assets—such as leasing fees from logistics fleets or profits from recycling operations—is shared with token holders.",
    ],
    icon: `<svg width="30" height="30" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
    <text x="10" y="40" font-size="40" font-family="Arial" fill="white">2</text>
</svg>`,
  },
  {
    title: "Dual Benefit Mechanism",
    features: [
      "Asset Revenue Participation: Investors receive a share of the profits generated by tokenized assets.",
      "Crypto Price Appreciation: As demand for our tokens grows, investors also benefit from potential price appreciation on secondary markets.",
    ],
    icon: `<svg width="30" height="30" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
    <text x="10" y="40" font-size="40" font-family="Arial" fill="white">3</text>
</svg>`,
  },
  {
    title: "Liquidity & Flexibility",
    features: [
      "Unlike traditional real estate or infrastructure investments, Alpha Tokens can be traded on regulated security token exchanges, offering flexibility and liquidity.",
    ],
    icon: `<svg width="30" height="30" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
    <text x="10" y="40" font-size="40" font-family="Arial" fill="white">4</text>
</svg>`,
  }
];

const solutions = [
  {
    title: "About Us",
    painPoint:
      "Alpha Token Fund leverages blockchain technology to create a secure and transparent investment ecosystem. By tokenizing real assets, including logistics infrastructure and industrial recycling, we allow investors to participate in asset-backed investments that generate real-world revenue.",
    agitatepainPoint:
      "Our mission is to bridge traditional finance with decentralized technology, ensuring investors gain exposure to high-value, income-generating assets while benefiting from blockchain’s liquidity and efficiency.",
    solution:
      "",
    img: visibilityDilemma,
  },
  /*{
    title: "Engagement Gap",
    painPoint:
      "Despite your efforts, audience engagement remains lackluster, and interactions are not translating into meaningful connections.",
    agitatepainPoint:
      "It's frustrating to see competitors effortlessly engaging their audience while your brand struggles to spark conversations. Your content deserves better results, and we have the solution.",
    solution:
      "Our proven engagement tactics ignite conversations, turning passive viewers into active participants. Explore how we bridge the engagement gap in our video walkthrough.",
    img: engagementGap,
  },
  {
    title: "Results in Hibernation",
    painPoint:
      "Your social media efforts aren't translating into tangible results, leaving you wondering if your investment is paying off.",
    agitatepainPoint:
      "It's disheartening when the metrics show little growth or impact. Your time and resources are valuable, and it's time to break free from the cycle of stagnant results.",
    solution:
      "Our data-driven approach ensures every action is purposeful, yielding measurable results. Dive into our video guide to witness how we turn social media activities into a powerful engine for your brand's success.",
    img: resultsInHibernation,
  },*/
];

const faqs = [
  {
    question: "How can social media marketing benefit my business?",
    answer:
      "Social media marketing can significantly benefit your business by increasing brand awareness, engaging your target audience, driving website traffic, and generating leads. It also allows for direct interaction with your customers, fostering brand loyalty and providing valuable insights into consumer behavior.",
  },
  {
    question: "What sets your agency apart from others?",
    answer:
      "Our agency stands out through a combination of tailored strategies, data-driven decision-making, and a commitment to client collaboration. We prioritize understanding your unique business goals and offer personalized solutions that deliver measurable results.",
  },
  {
    question: "How do you measure the success of social media campaigns?",
    answer:
      "We employ a comprehensive approach to measure campaign success. This includes tracking key performance indicators (KPIs) such as engagement metrics, conversion rates, reach, and customer feedback. Our goal is to provide you with transparent and actionable insights into the effectiveness of your social media efforts.",
  },
  {
    question:
      "Can you give examples of your successful social media campaigns?",
    answer:
      "Certainly! We have a portfolio of successful campaigns across various industries. Check out our Case Studies to see how we've helped businesses like yours achieve their social media goals.",
  },
  {
    question: "Do you offer customized social media strategies?",
    answer:
      "Absolutely. Our team specializes in creating customized strategies tailored to your brand, industry, and target audience. We believe in the power of uniqueness, and our strategies reflect your specific goals and aspirations.",
  },
  {
    question: "How do you handle negative comments or reviews on social media?",
    answer:
      "We have a proactive approach to managing online reputation. Our social listening tools help us monitor brand mentions in real-time. In case of negative comments, we respond promptly with empathy and seek resolutions. We believe in turning challenges into opportunities for improvement.",
  },
  {
    question: "What social media platforms do you work with?",
    answer:
      "We work with a wide range of social media platforms, including but not limited to Facebook, Instagram, Twitter, LinkedIn, Pinterest, and TikTok. Our strategies are adaptable to the platforms most relevant to your target audience.",
  },
  {
    question:
      "How often will I receive reports on the performance of my social media campaigns?",
    answer:
      "We provide regular and detailed reports on the performance of your social media campaigns. The frequency of reporting can be customized based on your preferences, with options for weekly, bi-weekly, or monthly updates.",
  },
  {
    question:
      "Is there ongoing support if I have questions or need adjustments to my strategy?",
    answer:
      "Absolutely. We offer ongoing support to address any questions or concerns you may have. Our team is readily available to assist you and can make adjustments to your strategy as needed to ensure it aligns with your evolving business goals.",
  },
  {
    question:
      "Can I see a demo or get a consultation before deciding to work with your agency?",
    answer:
      "Certainly! We offer free consultations and personalized demos to showcase our approach, discuss your needs, and determine how we can best support your business. Contact us to schedule a consultation.",
  },
];

const howToInvest = [
  {
    title: "Create an Account",
    features: [
      "Register on our platform and complete KYC verification.",
    ],
    icon: `<svg width="30" height="30" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
    <text x="10" y="40" font-size="40" font-family="Arial" fill="white">1</text>
</svg>
`,
  },
  {
    title: "Choose Your Investment",
    features: [
      "Select from tokenized assets such as logistics fleets and industrial recycling operations.",
    ],
    icon: `<svg width="30" height="30" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
    <text x="10" y="40" font-size="40" font-family="Arial" fill="white">2</text>
</svg>`,
  },
  {
    title: "Purchase Alpha Tokens",
    features: [
      "Secure your investment using fiat or cryptocurrency.",
    ],
    icon: `<svg width="30" height="30" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
    <text x="10" y="40" font-size="40" font-family="Arial" fill="white">3</text>
</svg>`,
  },
  {
    title: "Earn & Trade",
    features: [
      "Receive revenue from assets and trade tokens on compliant exchanges.",
    ],
    icon: `<svg width="30" height="30" viewBox="0 0 50 50" xmlns="http://www.w3.org/2000/svg">
    <text x="10" y="40" font-size="40" font-family="Arial" fill="white">4</text>
</svg>`,
  }
];

export { services, solutions, faqs, howToInvest };
